# Generated by Django 3.0.5 on 2020-04-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeenyURLs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teeny_url', models.CharField(max_length=10)),
                ('origin_url', models.CharField(max_length=9999)),
            ],
        ),
    ]
